version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt  # 设置 requirements.txt 文件路径

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip  # 只保留 HTML 格式
